### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by timdosanov** [GlebShikovec/p1#1]
Roadmap:

- [ ] Удалить не нужную логику из тестового проекта(модельки текстуры)

ADMIN UI
- [ ] Add start game button(admin have start game button) to start game

- [ ] Settings for number of imposters and crewmates

- [ ] _Time round_

- [ ] Support crewmate role(add appropiate actions, add died state)

- [ ] Support imposter role(add appropiate actions, at first add "kill" )

- [ ] End game clause

- [ ] Replicate kill action

- [ ] Add voting

- [ ] Imposters should recognize each other
